apiVersion: v1
kind: Secret
metadata:
  name: recsys-secret
  namespace: recsys
type: Opaque
stringData:
  MONGO_DB: RecSys
  MONGO_URL: mongodb+srv://a3ryn:spidy1576@cluster0.mcps6ce.mongodb.net/
  SECRET_ACCESS_TOKEN: b08f81022406b4755979c8f631a53e5a
3734653731
6263
