apiVersion: v1
kind: Service
metadata:
  name: recsys-service
  namespace: recsys
spec:
  selector:
    app: recsys-backend
  ports:
    - protocol: TCP
      port: 80         # this is what external traffic sees
      targetPort: 8000 # this is where the pod is listening
  type: ClusterIP
